name: Build and Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (leave empty to use package.json version)'
        required: false

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Update version if provided
        if: inputs.version != ''
        run: npm version ${{ inputs.version }} --no-git-tag-version

      - name: Build extensions
        run: |
          npm run build
          npm run build:firefox
          npm run build:edge

      - name: Create ZIP files
        run: |
          npm run zip
          npm run zip:firefox
          npm run zip:edge

      - name: Get version
        id: get-version
        run: echo "version=$(node -e "console.log(require('./package.json').version)")" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.get-version.outputs.version }}
          release_name: KnoxLink v${{ steps.get-version.outputs.version }}
          draft: false
          prerelease: false

      - name: Upload Chrome ZIP to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./.output/knoxlink-${{ steps.get-version.outputs.version }}-chrome.zip
          asset_name: knoxlink-${{ steps.get-version.outputs.version }}-chrome.zip
          asset_content_type: application/zip

      - name: Upload Firefox ZIP to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./.output/knoxlink-${{ steps.get-version.outputs.version }}-firefox.zip
          asset_name: knoxlink-${{ steps.get-version.outputs.version }}-firefox.zip
          asset_content_type: application/zip

      - name: Upload Firefox Sources ZIP to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./.output/knoxlink-${{ steps.get-version.outputs.version }}-sources.zip
          asset_name: knoxlink-${{ steps.get-version.outputs.version }}-sources.zip
          asset_content_type: application/zip

      - name: Upload Edge ZIP to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./.output/knoxlink-${{ steps.get-version.outputs.version }}-chrome.zip
          asset_name: knoxlink-${{ steps.get-version.outputs.version }}-edge.zip
          asset_content_type: application/zip